baseURL = "https://peterjanrosanna.com"
disqusShortname = "Wedding PJ&Roos"
languageCode = "en-us"
languageName = "En"
paginate = "6"
theme = "persian-hugo"
title = "PJ&Roos"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Contact"
url = "contact"
weight = 6
[[menu.main]]
name = "Gifts"
url = "gifts"
weight = 5
[[menu.main]]
name = "Travel & Stay"
url = "travel"
weight = 4
[[menu.main]]
name = "Ceremony & Reception"
url = "schedule"
weight = 3
[[menu.main]]
name = "Invitation"
url = "invitation"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = ""
contact_form_action = ""
copyright = ""
description = ""
logo = "images/logo.png"
search = true
[params.cookies]
enable = false
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
